spring.datasource.url=jdbc:postgresql://localhost:5432/docsy
spring.datasource.username=jkuiplo
spring.datasource.password=12345
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true